project:
  type: website
  output-dir: docs

website:
  title: "ISPOR New Zealand Chapter"
  search: false
  navbar:
    title: false
    logo: _images/ISPOR_NewZealandChapter_Logo.jpg
    background: white
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - href: nz-chapter.qmd
            text: NZ Chapter
          - href: what-is-ispor.qmd
            text: What is ISPOR?
          - href: contact.qmd
            text: Contact us
      - href: events.qmd
        text: Events & News
      - href: membership.qmd
        text: Membership

format:
  html:
    theme: flatly
    css: styles.css
    template-partials: title-metadata.html
