---
title: "Membership"
---

::: {style="font-size: larger"}
ISPOR (NZ) is the only scientific organisation in New Zealand that brings together health care scientists, professionals and providers, academics, procurement and budget holders, suppliers, publishers, policy makers and others interested in the economics of healthcare interventions.
:::

Our aim is to provide an environment that enables collaborative sharing of knowledge and to act as a resource for those interested in health technology economics and outcomes research.

Memberships are currently being accepted. To enrol as a member of ISPOR (NZ) please fill out the form below.

## Benefits of ISPOR (NZ) membership

* Linkage outside the usual professional groups.
* Free or discounted educational workshops and webinar tutorials.
* Regular updates about research, PHARMAC and other New Zealand health funders, ISPOR International and upcoming conferences.

We hold bi-annual national events, usually in Auckland or Wellington, and regular webinars to keep members up with the latest local and international thinking on health economics.

## Cost

* $80 non-students
* $50 members of ISPOR International
* $0 students (with proof of student status)

If you haven’t already, connect with us on [LinkedIn](http://nz.linkedin.com/pub/ispor-nzchapter/).

We look forward to your membership and seeing you at the events. In the meantime, if you have any questions or suggestions, please get in touch: <ispornewzealand@gmail.com>

<br>

***

## Membership registration form{style="max-width:800px; margin:auto"}

<script src="https://www.cognitoforms.com/f/seamless.js" data-key="_dW8dQmWak6rztGhzLHX3g" data-form="3"></script>

