## Improving Healthcare Decisions

ISPOR is dedicated to improving healthcare decision making. We believe that every healthcare decision should be informed by the best scientific research. Toward that goal, the Society’s mission is to promote health economics and outcomes research excellence to improve decision making for health globally.

## ISPOR---The Professional Society for Health Economics and Outcomes Research

ISPOR—the professional society for health economics and outcomes research (HEOR)—is an international, multistakeholder, nonprofit organization. The Society is the leading source for scientific conferences, peer-reviewed and MEDLINE®-indexed publications, good practices guidance, education, collaboration, and tools/resources in the HEOR field.

##The Global HEOR Community

As the field of HEOR has grown in importance, ISPOR’s community has expanded to more than 20,000 individual and chapter members from 110+ countries worldwide. The Society’s membership includes a wide variety of healthcare stakeholders, including researchers and academicians, assessors and regulators, payers and policy makers, the life sciences industry, healthcare providers, and patient engagement organizations. The Society has served as an unbiased resource and catalyst for innovation in the field for more than 20 years.

[To find out more about ISPOR visit the ISPOR Global Home Page.](https://www.ispor.org/)
