---
title: "ISPOR NZ webinar"
description: "17 March 2022"
date: "2022-03-03"
categories: Past events
---

<h3 style="text-align:center">New Developments in Economic Evaluation:<br>Could Aotearoa New Zealand be a Petri Dish?</h3>

<br>

<h3 style="text-align:center">Professor Paula Lorgelly, University of Auckland</h3>
<h4 style="text-align:center">*Thursday 17 March 2022, 9am*</h4>

<br>

We are very pleased to announce the first presentation in the ISPOR NZ 2022 webinar series.

**Professor Paula Lorgelly**, recently-appointed Chair of Health Economics at the University of Auckland, will present on new developments in health economic evaluation and their relevance to Aotearoa New Zealand.

Paula left New Zealand in 1999 with a submitted PhD in development economics and a teaching knowledge of health economics (thanks to the slides of Paul Hansen and Nancy Devlin).  She returns in 2022 as a health economist with considerable experience in undertaking economic evaluations and the application of new methods. In this talk she will present some methodological challenges that she’d like to work on in Aotearoa. This includes understanding how to measure productivity loss, how equity features in HTA guidelines and what is the societal perspective and how could it include carbon to tackle the climate crisis.  Paula would welcome feedback on these ideas and approaches to collaborate.

##### *About the presenter*
Paula Lorgelly is a Professor of Health Economics at the University of Auckland. She has a distinguished career working in academia in the United Kingdom, Australia and New Zealand (including a visiting position in Germany), and the independent sector in the United Kingdom. Whilst in Australia she was a member of the Economics Sub-Committee of the Pharmaceutical Benefits Advisory Committee (PBAC), and in this capacity provided advice on the effectiveness and cost-effectiveness of treatments seeking reimbursement on the Pharmaceutical Benefits Scheme. Her research interests span three defined areas: the determinants of health and healthcare, economic evaluation and outcome measurement. She has worked across the health and medical spectrum and much of her research focuses on cancer, and more recently on long COVID. She has experience across a range of methodologies including the analysis of trial data, decision analytic modelling, econometric analyses of health surveys including panel data, preference elicitation using discrete choice experiments and qualitative analyses. Paula is the outgoing national organiser of the UK Health Economists’ Study Group, the co-chair of the forthcoming iHEA Congress, a member of the EuroQol Group, and on the Editorial Boards of the *Journal of Cancer Policy*, *The Patient* and the *International Journal of Environmental Research and Public Health*.
